version: "2.4"

x-build: &build
  build:
    context: .
    dockerfile: Dockerfile
    args:
      CRYSTAL_VERSION: "1.0.0"
      USER_ID: "${UID:-1000}"
  image: skaia-crystal:1.2.0
  user: "${UID:-1000}:${UID:-1000}"
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *build
  restart: "no"
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
  depends_on:
    rabbitmq:
      condition: service_healthy

services:
  runner:
    <<: *backend
    command: /bin/sh

  rabbitmq:
    image: rabbitmq:3.8.2-management
    restart: "no"
    ports:
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  rabbitmq_data:
