name: CI

on:
  pull_request:

  push:
    branches:
      - main

env:
  CRYSTAL_VERSION: '1.0.0'
  CI: true

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ env.CRYSTAL_VERSION }}
      - run: shards install --ignore-crystal-version
      - run: crystal tool format --check

  Code-Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ env.CRYSTAL_VERSION }}
      - run: shards install --ignore-crystal-version
      - run: ./bin/ameba

  Specs:
    needs: [Linter, Code-Analysis]
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - crystal: 1.0.0
            experimental: false
          - crystal: latest
            experimental: false
          - crystal: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - run: shards install --ignore-crystal-version
      - run: crystal spec
